// ═══════════════════════════════════════════════════════════════
//  PAÍSES DEL MUNDO — con moneda local y salario mínimo estimado
//  Salario mínimo: valor aproximado por hora en moneda local.
//  Se puede refrescar vía API del Banco Mundial.
//  NUNCA se convierte a otra moneda — todo es en moneda local.
// ═══════════════════════════════════════════════════════════════

class Country {
  final String name;        // Nombre en español
  final String flag;        // Emoji bandera
  final String code;        // ISO 3166-1 alpha-2
  final String currency;    // Nombre de la moneda
  final String currencyCode;// ISO 4217 (USD, EUR, MXN…)
  final String currencySymbol; // $, €, £, ¥…
  final double minWagePerHour; // Salario mínimo estimado por hora en moneda local

  const Country({
    required this.name,
    required this.flag,
    required this.code,
    required this.currency,
    required this.currencyCode,
    required this.currencySymbol,
    required this.minWagePerHour,
  });
}

const List<Country> kCountries = [
  Country(name: 'Afganistán',           flag: '🇦🇫', code: 'AF', currency: 'Afgani afgano',         currencyCode: 'AFN', currencySymbol: '؋',  minWagePerHour: 30),
  Country(name: 'Albania',              flag: '🇦🇱', code: 'AL', currency: 'Lek albanés',             currencyCode: 'ALL', currencySymbol: 'L',  minWagePerHour: 80),
  Country(name: 'Alemania',             flag: '🇩🇪', code: 'DE', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 12),
  Country(name: 'Andorra',              flag: '🇦🇩', code: 'AD', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 9),
  Country(name: 'Angola',               flag: '🇦🇴', code: 'AO', currency: 'Kwanza angoleño',         currencyCode: 'AOA', currencySymbol: 'Kz', minWagePerHour: 175),
  Country(name: 'Antigua y Barbuda',    flag: '🇦🇬', code: 'AG', currency: 'Dólar del Caribe Oriental',currencyCode: 'XCD', currencySymbol: '\$',  minWagePerHour: 7),
  Country(name: 'Arabia Saudita',       flag: '🇸🇦', code: 'SA', currency: 'Riyal saudí',             currencyCode: 'SAR', currencySymbol: '﷼', minWagePerHour: 18),
  Country(name: 'Argelia',              flag: '🇩🇿', code: 'DZ', currency: 'Dinar argelino',          currencyCode: 'DZD', currencySymbol: 'د.ج',minWagePerHour: 280),
  Country(name: 'Argentina',            flag: '🇦🇷', code: 'AR', currency: 'Peso argentino',          currencyCode: 'ARS', currencySymbol: '\$',  minWagePerHour: 2800),
  Country(name: 'Armenia',              flag: '🇦🇲', code: 'AM', currency: 'Dram armenio',            currencyCode: 'AMD', currencySymbol: '֏',  minWagePerHour: 710),
  Country(name: 'Australia',            flag: '🇦🇺', code: 'AU', currency: 'Dólar australiano',       currencyCode: 'AUD', currencySymbol: '\$',  minWagePerHour: 23),
  Country(name: 'Austria',              flag: '🇦🇹', code: 'AT', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 12),
  Country(name: 'Azerbaiyán',           flag: '🇦🇿', code: 'AZ', currency: 'Manat azerbaiyano',       currencyCode: 'AZN', currencySymbol: '₼',  minWagePerHour: 3),
  Country(name: 'Bahamas',              flag: '🇧🇸', code: 'BS', currency: 'Dólar bahameño',          currencyCode: 'BSD', currencySymbol: '\$',  minWagePerHour: 5),
  Country(name: 'Bangladés',            flag: '🇧🇩', code: 'BD', currency: 'Taka bangladesí',         currencyCode: 'BDT', currencySymbol: '৳',  minWagePerHour: 95),
  Country(name: 'Barbados',             flag: '🇧🇧', code: 'BB', currency: 'Dólar de Barbados',       currencyCode: 'BBD', currencySymbol: '\$',  minWagePerHour: 10),
  Country(name: 'Baréin',               flag: '🇧🇭', code: 'BH', currency: 'Dinar bareiní',           currencyCode: 'BHD', currencySymbol: 'BD', minWagePerHour: 1),
  Country(name: 'Bélgica',              flag: '🇧🇪', code: 'BE', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 14),
  Country(name: 'Belice',               flag: '🇧🇿', code: 'BZ', currency: 'Dólar de Belice',         currencyCode: 'BZD', currencySymbol: '\$',  minWagePerHour: 7),
  Country(name: 'Benín',                flag: '🇧🇯', code: 'BJ', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 280),
  Country(name: 'Bielorrusia',          flag: '🇧🇾', code: 'BY', currency: 'Rublo bielorruso',        currencyCode: 'BYN', currencySymbol: 'Br', minWagePerHour: 5),
  Country(name: 'Bolivia',              flag: '🇧🇴', code: 'BO', currency: 'Boliviano',               currencyCode: 'BOB', currencySymbol: 'Bs', minWagePerHour: 19),
  Country(name: 'Bosnia y Herzegovina', flag: '🇧🇦', code: 'BA', currency: 'Marco convertible',       currencyCode: 'BAM', currencySymbol: 'KM', minWagePerHour: 3),
  Country(name: 'Botsuana',             flag: '🇧🇼', code: 'BW', currency: 'Pula botsuanesa',         currencyCode: 'BWP', currencySymbol: 'P',  minWagePerHour: 9),
  Country(name: 'Brasil',               flag: '🇧🇷', code: 'BR', currency: 'Real brasileño',          currencyCode: 'BRL', currencySymbol: 'R\$', minWagePerHour: 8),
  Country(name: 'Brunéi',               flag: '🇧🇳', code: 'BN', currency: 'Dólar de Brunéi',         currencyCode: 'BND', currencySymbol: '\$',  minWagePerHour: 6),
  Country(name: 'Bulgaria',             flag: '🇧🇬', code: 'BG', currency: 'Lev búlgaro',             currencyCode: 'BGN', currencySymbol: 'лв', minWagePerHour: 4),
  Country(name: 'Burkina Faso',         flag: '🇧🇫', code: 'BF', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 250),
  Country(name: 'Burundi',              flag: '🇧🇮', code: 'BI', currency: 'Franco burundés',         currencyCode: 'BIF', currencySymbol: 'Fr', minWagePerHour: 800),
  Country(name: 'Bután',                flag: '🇧🇹', code: 'BT', currency: 'Ngultrum butanés',        currencyCode: 'BTN', currencySymbol: 'Nu', minWagePerHour: 65),
  Country(name: 'Cabo Verde',           flag: '🇨🇻', code: 'CV', currency: 'Escudo caboverdiano',     currencyCode: 'CVE', currencySymbol: '\$',  minWagePerHour: 120),
  Country(name: 'Camboya',              flag: '🇰🇭', code: 'KH', currency: 'Riel camboyano',          currencyCode: 'KHR', currencySymbol: '៛',  minWagePerHour: 3000),
  Country(name: 'Camerún',              flag: '🇨🇲', code: 'CM', currency: 'Franco CFA de África Central', currencyCode: 'XAF', currencySymbol: 'Fr', minWagePerHour: 340),
  Country(name: 'Canadá',               flag: '🇨🇦', code: 'CA', currency: 'Dólar canadiense',        currencyCode: 'CAD', currencySymbol: '\$',  minWagePerHour: 17),
  Country(name: 'Catar',                flag: '🇶🇦', code: 'QA', currency: 'Riyal catarí',            currencyCode: 'QAR', currencySymbol: '﷼', minWagePerHour: 8),
  Country(name: 'Chad',                 flag: '🇹🇩', code: 'TD', currency: 'Franco CFA de África Central', currencyCode: 'XAF', currencySymbol: 'Fr', minWagePerHour: 330),
  Country(name: 'Chile',                flag: '🇨🇱', code: 'CL', currency: 'Peso chileno',            currencyCode: 'CLP', currencySymbol: '\$',  minWagePerHour: 2300),
  Country(name: 'China',                flag: '🇨🇳', code: 'CN', currency: 'Yuan chino',              currencyCode: 'CNY', currencySymbol: '¥',  minWagePerHour: 25),
  Country(name: 'Chipre',               flag: '🇨🇾', code: 'CY', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 10),
  Country(name: 'Colombia',             flag: '🇨🇴', code: 'CO', currency: 'Peso colombiano',         currencyCode: 'COP', currencySymbol: '\$',  minWagePerHour: 6250),
  Country(name: 'Comoras',              flag: '🇰🇲', code: 'KM', currency: 'Franco comorense',        currencyCode: 'KMF', currencySymbol: 'Fr', minWagePerHour: 500),
  Country(name: 'Congo (Rep. Dem.)',    flag: '🇨🇩', code: 'CD', currency: 'Franco congoleño',        currencyCode: 'CDF', currencySymbol: 'Fr', minWagePerHour: 3500),
  Country(name: 'Congo (Rep.)',         flag: '🇨🇬', code: 'CG', currency: 'Franco CFA de África Central', currencyCode: 'XAF', currencySymbol: 'Fr', minWagePerHour: 500),
  Country(name: 'Corea del Norte',      flag: '🇰🇵', code: 'KP', currency: 'Won norcoreano',          currencyCode: 'KPW', currencySymbol: '₩',  minWagePerHour: 450),
  Country(name: 'Corea del Sur',        flag: '🇰🇷', code: 'KR', currency: 'Won surcoreano',          currencyCode: 'KRW', currencySymbol: '₩',  minWagePerHour: 9860),
  Country(name: 'Costa de Marfil',      flag: '🇨🇮', code: 'CI', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 380),
  Country(name: 'Costa Rica',           flag: '🇨🇷', code: 'CR', currency: 'Colón costarricense',     currencyCode: 'CRC', currencySymbol: '₡',  minWagePerHour: 1900),
  Country(name: 'Croacia',              flag: '🇭🇷', code: 'HR', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 6),
  Country(name: 'Cuba',                 flag: '🇨🇺', code: 'CU', currency: 'Peso cubano',             currencyCode: 'CUP', currencySymbol: '\$',  minWagePerHour: 250),
  Country(name: 'Dinamarca',            flag: '🇩🇰', code: 'DK', currency: 'Corona danesa',           currencyCode: 'DKK', currencySymbol: 'kr', minWagePerHour: 110),
  Country(name: 'Dominica',             flag: '🇩🇲', code: 'DM', currency: 'Dólar del Caribe Oriental',currencyCode: 'XCD', currencySymbol: '\$',  minWagePerHour: 7),
  Country(name: 'Ecuador',              flag: '🇪🇨', code: 'EC', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 2.25),
  Country(name: 'Egipto',               flag: '🇪🇬', code: 'EG', currency: 'Libra egipcia',           currencyCode: 'EGP', currencySymbol: '£',  minWagePerHour: 50),
  Country(name: 'El Salvador',          flag: '🇸🇻', code: 'SV', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 1.5),
  Country(name: 'Emiratos Árabes',      flag: '🇦🇪', code: 'AE', currency: 'Dírham emiratí',          currencyCode: 'AED', currencySymbol: 'د.إ',minWagePerHour: 18),
  Country(name: 'Eritrea',              flag: '🇪🇷', code: 'ER', currency: 'Nakfa eritreo',           currencyCode: 'ERN', currencySymbol: 'Nkf',minWagePerHour: 30),
  Country(name: 'Eslovaquia',           flag: '🇸🇰', code: 'SK', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 5),
  Country(name: 'Eslovenia',            flag: '🇸🇮', code: 'SI', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 8),
  Country(name: 'España',               flag: '🇪🇸', code: 'ES', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 8),
  Country(name: 'Estados Unidos',       flag: '🇺🇸', code: 'US', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 7.25),
  Country(name: 'Estonia',              flag: '🇪🇪', code: 'EE', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 8),
  Country(name: 'Etiopía',              flag: '🇪🇹', code: 'ET', currency: 'Birr etíope',             currencyCode: 'ETB', currencySymbol: 'Br', minWagePerHour: 18),
  Country(name: 'Filipinas',            flag: '🇵🇭', code: 'PH', currency: 'Peso filipino',           currencyCode: 'PHP', currencySymbol: '₱',  minWagePerHour: 89),
  Country(name: 'Finlandia',            flag: '🇫🇮', code: 'FI', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 14),
  Country(name: 'Fiyi',                 flag: '🇫🇯', code: 'FJ', currency: 'Dólar fiyiano',           currencyCode: 'FJD', currencySymbol: '\$',  minWagePerHour: 4),
  Country(name: 'Francia',              flag: '🇫🇷', code: 'FR', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 11.65),
  Country(name: 'Gabón',                flag: '🇬🇦', code: 'GA', currency: 'Franco CFA de África Central', currencyCode: 'XAF', currencySymbol: 'Fr', minWagePerHour: 800),
  Country(name: 'Gambia',               flag: '🇬🇲', code: 'GM', currency: 'Dalasi gambiano',         currencyCode: 'GMD', currencySymbol: 'D',  minWagePerHour: 30),
  Country(name: 'Georgia',              flag: '🇬🇪', code: 'GE', currency: 'Lari georgiano',          currencyCode: 'GEL', currencySymbol: '₾',  minWagePerHour: 4),
  Country(name: 'Ghana',                flag: '🇬🇭', code: 'GH', currency: 'Cedi ghanés',             currencyCode: 'GHS', currencySymbol: '₵',  minWagePerHour: 7),
  Country(name: 'Granada',              flag: '🇬🇩', code: 'GD', currency: 'Dólar del Caribe Oriental',currencyCode: 'XCD', currencySymbol: '\$',  minWagePerHour: 6),
  Country(name: 'Grecia',               flag: '🇬🇷', code: 'GR', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 7),
  Country(name: 'Guatemala',            flag: '🇬🇹', code: 'GT', currency: 'Quetzal guatemalteco',    currencyCode: 'GTQ', currencySymbol: 'Q',  minWagePerHour: 12),
  Country(name: 'Guinea',               flag: '🇬🇳', code: 'GN', currency: 'Franco guineano',         currencyCode: 'GNF', currencySymbol: 'Fr', minWagePerHour: 8000),
  Country(name: 'Guinea Ecuatorial',    flag: '🇬🇶', code: 'GQ', currency: 'Franco CFA de África Central', currencyCode: 'XAF', currencySymbol: 'Fr', minWagePerHour: 450),
  Country(name: 'Guinea-Bisáu',         flag: '🇬🇼', code: 'GW', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 250),
  Country(name: 'Guyana',               flag: '🇬🇾', code: 'GY', currency: 'Dólar guyanés',           currencyCode: 'GYD', currencySymbol: '\$',  minWagePerHour: 400),
  Country(name: 'Haití',                flag: '🇭🇹', code: 'HT', currency: 'Gourde haitiano',         currencyCode: 'HTG', currencySymbol: 'G',  minWagePerHour: 75),
  Country(name: 'Honduras',             flag: '🇭🇳', code: 'HN', currency: 'Lempira hondureño',       currencyCode: 'HNL', currencySymbol: 'L',  minWagePerHour: 45),
  Country(name: 'Hungría',              flag: '🇭🇺', code: 'HU', currency: 'Forinto húngaro',         currencyCode: 'HUF', currencySymbol: 'Ft', minWagePerHour: 1100),
  Country(name: 'India',                flag: '🇮🇳', code: 'IN', currency: 'Rupia india',             currencyCode: 'INR', currencySymbol: '₹',  minWagePerHour: 55),
  Country(name: 'Indonesia',            flag: '🇮🇩', code: 'ID', currency: 'Rupia indonesia',         currencyCode: 'IDR', currencySymbol: 'Rp', minWagePerHour: 17000),
  Country(name: 'Irak',                 flag: '🇮🇶', code: 'IQ', currency: 'Dinar iraquí',            currencyCode: 'IQD', currencySymbol: 'ع.د',minWagePerHour: 3000),
  Country(name: 'Irán',                 flag: '🇮🇷', code: 'IR', currency: 'Rial iraní',              currencyCode: 'IRR', currencySymbol: '﷼', minWagePerHour: 85000),
  Country(name: 'Irlanda',              flag: '🇮🇪', code: 'IE', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 12.70),
  Country(name: 'Islandia',             flag: '🇮🇸', code: 'IS', currency: 'Corona islandesa',        currencyCode: 'ISK', currencySymbol: 'kr', minWagePerHour: 1400),
  Country(name: 'Islas Marshall',       flag: '🇲🇭', code: 'MH', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 3),
  Country(name: 'Islas Salomón',        flag: '🇸🇧', code: 'SB', currency: 'Dólar de las Islas Salomón',currencyCode: 'SBD', currencySymbol: '\$',minWagePerHour: 7),
  Country(name: 'Israel',               flag: '🇮🇱', code: 'IL', currency: 'Séquel israelí',          currencyCode: 'ILS', currencySymbol: '₪',  minWagePerHour: 32),
  Country(name: 'Italia',               flag: '🇮🇹', code: 'IT', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 9),
  Country(name: 'Jamaica',              flag: '🇯🇲', code: 'JM', currency: 'Dólar jamaicano',         currencyCode: 'JMD', currencySymbol: '\$',  minWagePerHour: 600),
  Country(name: 'Japón',                flag: '🇯🇵', code: 'JP', currency: 'Yen japonés',             currencyCode: 'JPY', currencySymbol: '¥',  minWagePerHour: 1000),
  Country(name: 'Jordania',             flag: '🇯🇴', code: 'JO', currency: 'Dinar jordano',           currencyCode: 'JOD', currencySymbol: 'د.ا',minWagePerHour: 3),
  Country(name: 'Kazajistán',           flag: '🇰🇿', code: 'KZ', currency: 'Tenge kazajo',            currencyCode: 'KZT', currencySymbol: '₸',  minWagePerHour: 1600),
  Country(name: 'Kenia',                flag: '🇰🇪', code: 'KE', currency: 'Chelín keniano',          currencyCode: 'KES', currencySymbol: 'KSh',minWagePerHour: 260),
  Country(name: 'Kirguistán',           flag: '🇰🇬', code: 'KG', currency: 'Som kirguís',             currencyCode: 'KGS', currencySymbol: 'с',  minWagePerHour: 110),
  Country(name: 'Kiribati',             flag: '🇰🇮', code: 'KI', currency: 'Dólar australiano',       currencyCode: 'AUD', currencySymbol: '\$',  minWagePerHour: 3),
  Country(name: 'Kosovo',               flag: '🇽🇰', code: 'XK', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 2),
  Country(name: 'Kuwait',               flag: '🇰🇼', code: 'KW', currency: 'Dinar kuwaití',           currencyCode: 'KWD', currencySymbol: 'د.ك',minWagePerHour: 2),
  Country(name: 'Laos',                 flag: '🇱🇦', code: 'LA', currency: 'Kip laosiano',            currencyCode: 'LAK', currencySymbol: '₭',  minWagePerHour: 8000),
  Country(name: 'Lesoto',               flag: '🇱🇸', code: 'LS', currency: 'Loti lesotense',          currencyCode: 'LSL', currencySymbol: 'L',  minWagePerHour: 14),
  Country(name: 'Letonia',              flag: '🇱🇻', code: 'LV', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 6),
  Country(name: 'Líbano',               flag: '🇱🇧', code: 'LB', currency: 'Libra libanesa',          currencyCode: 'LBP', currencySymbol: 'ل.ل',minWagePerHour: 22500),
  Country(name: 'Liberia',              flag: '🇱🇷', code: 'LR', currency: 'Dólar liberiano',         currencyCode: 'LRD', currencySymbol: '\$',  minWagePerHour: 35),
  Country(name: 'Libia',                flag: '🇱🇾', code: 'LY', currency: 'Dinar libio',             currencyCode: 'LYD', currencySymbol: 'ل.د',minWagePerHour: 7),
  Country(name: 'Liechtenstein',        flag: '🇱🇮', code: 'LI', currency: 'Franco suizo',            currencyCode: 'CHF', currencySymbol: 'Fr', minWagePerHour: 22),
  Country(name: 'Lituania',             flag: '🇱🇹', code: 'LT', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 7),
  Country(name: 'Luxemburgo',           flag: '🇱🇺', code: 'LU', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 15),
  Country(name: 'Madagascar',           flag: '🇲🇬', code: 'MG', currency: 'Ariary malgache',         currencyCode: 'MGA', currencySymbol: 'Ar', minWagePerHour: 2200),
  Country(name: 'Malasia',              flag: '🇲🇾', code: 'MY', currency: 'Ringgit malayo',          currencyCode: 'MYR', currencySymbol: 'RM', minWagePerHour: 7),
  Country(name: 'Malaui',               flag: '🇲🇼', code: 'MW', currency: 'Kwacha malauí',           currencyCode: 'MWK', currencySymbol: 'MK', minWagePerHour: 800),
  Country(name: 'Maldivas',             flag: '🇲🇻', code: 'MV', currency: 'Rufiyaa maldivo',         currencyCode: 'MVR', currencySymbol: 'Rf', minWagePerHour: 25),
  Country(name: 'Malí',                 flag: '🇲🇱', code: 'ML', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 450),
  Country(name: 'Malta',                flag: '🇲🇹', code: 'MT', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 8),
  Country(name: 'Marruecos',            flag: '🇲🇦', code: 'MA', currency: 'Dírham marroquí',         currencyCode: 'MAD', currencySymbol: 'د.م.',minWagePerHour: 15),
  Country(name: 'Mauricio',             flag: '🇲🇺', code: 'MU', currency: 'Rupia mauriciana',        currencyCode: 'MUR', currencySymbol: 'Rs', minWagePerHour: 80),
  Country(name: 'Mauritania',           flag: '🇲🇷', code: 'MR', currency: 'Uguiya mauritana',        currencyCode: 'MRU', currencySymbol: 'UM', minWagePerHour: 90),
  Country(name: 'México',               flag: '🇲🇽', code: 'MX', currency: 'Peso mexicano',           currencyCode: 'MXN', currencySymbol: '\$',  minWagePerHour: 28),
  Country(name: 'Micronesia',           flag: '🇫🇲', code: 'FM', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 2),
  Country(name: 'Moldavia',             flag: '🇲🇩', code: 'MD', currency: 'Leu moldavo',             currencyCode: 'MDL', currencySymbol: 'L',  minWagePerHour: 50),
  Country(name: 'Mónaco',               flag: '🇲🇨', code: 'MC', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 12),
  Country(name: 'Mongolia',             flag: '🇲🇳', code: 'MN', currency: 'Tugrik mongol',           currencyCode: 'MNT', currencySymbol: '₮',  minWagePerHour: 2800),
  Country(name: 'Montenegro',           flag: '🇲🇪', code: 'ME', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 4),
  Country(name: 'Mozambique',           flag: '🇲🇿', code: 'MZ', currency: 'Metical mozambiqueño',    currencyCode: 'MZN', currencySymbol: 'MT', minWagePerHour: 60),
  Country(name: 'Myanmar',              flag: '🇲🇲', code: 'MM', currency: 'Kyat birmano',            currencyCode: 'MMK', currencySymbol: 'K',  minWagePerHour: 1200),
  Country(name: 'Namibia',              flag: '🇳🇦', code: 'NA', currency: 'Dólar namibio',           currencyCode: 'NAD', currencySymbol: '\$',  minWagePerHour: 18),
  Country(name: 'Nauru',                flag: '🇳🇷', code: 'NR', currency: 'Dólar australiano',       currencyCode: 'AUD', currencySymbol: '\$',  minWagePerHour: 5),
  Country(name: 'Nepal',                flag: '🇳🇵', code: 'NP', currency: 'Rupia nepalesa',          currencyCode: 'NPR', currencySymbol: 'Rs', minWagePerHour: 75),
  Country(name: 'Nicaragua',            flag: '🇳🇮', code: 'NI', currency: 'Córdoba nicaragüense',    currencyCode: 'NIO', currencySymbol: 'C\$', minWagePerHour: 45),
  Country(name: 'Níger',                flag: '🇳🇪', code: 'NE', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 200),
  Country(name: 'Nigeria',              flag: '🇳🇬', code: 'NG', currency: 'Naira nigeriana',         currencyCode: 'NGN', currencySymbol: '₦',  minWagePerHour: 750),
  Country(name: 'Noruega',              flag: '🇳🇴', code: 'NO', currency: 'Corona noruega',          currencyCode: 'NOK', currencySymbol: 'kr', minWagePerHour: 175),
  Country(name: 'Nueva Zelanda',        flag: '🇳🇿', code: 'NZ', currency: 'Dólar neozelandés',       currencyCode: 'NZD', currencySymbol: '\$',  minWagePerHour: 22.70),
  Country(name: 'Omán',                 flag: '🇴🇲', code: 'OM', currency: 'Rial omaní',              currencyCode: 'OMR', currencySymbol: 'ر.ع.',minWagePerHour: 1.5),
  Country(name: 'Países Bajos',         flag: '🇳🇱', code: 'NL', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 13),
  Country(name: 'Pakistán',             flag: '🇵🇰', code: 'PK', currency: 'Rupia pakistaní',         currencyCode: 'PKR', currencySymbol: 'Rs', minWagePerHour: 400),
  Country(name: 'Palaos',               flag: '🇵🇼', code: 'PW', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 4),
  Country(name: 'Palestina',            flag: '🇵🇸', code: 'PS', currency: 'Shekel israelí',          currencyCode: 'ILS', currencySymbol: '₪',  minWagePerHour: 17),
  Country(name: 'Panamá',               flag: '🇵🇦', code: 'PA', currency: 'Balboa panameño',         currencyCode: 'PAB', currencySymbol: 'B/', minWagePerHour: 2.70),
  Country(name: 'Papúa Nueva Guinea',   flag: '🇵🇬', code: 'PG', currency: 'Kina de Papúa',          currencyCode: 'PGK', currencySymbol: 'K',  minWagePerHour: 11),
  Country(name: 'Paraguay',             flag: '🇵🇾', code: 'PY', currency: 'Guaraní paraguayo',       currencyCode: 'PYG', currencySymbol: '₲',  minWagePerHour: 12000),
  Country(name: 'Perú',                 flag: '🇵🇪', code: 'PE', currency: 'Sol peruano',             currencyCode: 'PEN', currencySymbol: 'S/', minWagePerHour: 5.40),
  Country(name: 'Polonia',              flag: '🇵🇱', code: 'PL', currency: 'Esloti polaco',           currencyCode: 'PLN', currencySymbol: 'zł', minWagePerHour: 25),
  Country(name: 'Portugal',             flag: '🇵🇹', code: 'PT', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 5.70),
  Country(name: 'Reino Unido',          flag: '🇬🇧', code: 'GB', currency: 'Libra esterlina',         currencyCode: 'GBP', currencySymbol: '£',  minWagePerHour: 11.44),
  Country(name: 'República Centroafricana', flag: '🇨🇫', code: 'CF', currency: 'Franco CFA de África Central', currencyCode: 'XAF', currencySymbol: 'Fr', minWagePerHour: 300),
  Country(name: 'República Checa',      flag: '🇨🇿', code: 'CZ', currency: 'Corona checa',            currencyCode: 'CZK', currencySymbol: 'Kč', minWagePerHour: 96),
  Country(name: 'República Dominicana', flag: '🇩🇴', code: 'DO', currency: 'Peso dominicano',         currencyCode: 'DOP', currencySymbol: '\$',  minWagePerHour: 110),
  Country(name: 'Ruanda',               flag: '🇷🇼', code: 'RW', currency: 'Franco ruandés',          currencyCode: 'RWF', currencySymbol: 'Fr', minWagePerHour: 600),
  Country(name: 'Rumanía',              flag: '🇷🇴', code: 'RO', currency: 'Leu rumano',              currencyCode: 'RON', currencySymbol: 'lei',minWagePerHour: 16),
  Country(name: 'Rusia',                flag: '🇷🇺', code: 'RU', currency: 'Rublo ruso',              currencyCode: 'RUB', currencySymbol: '₽',  minWagePerHour: 200),
  Country(name: 'Samoa',                flag: '🇼🇸', code: 'WS', currency: 'Tālā samoano',            currencyCode: 'WST', currencySymbol: 'T',  minWagePerHour: 5),
  Country(name: 'San Cristóbal y Nieves',flag: '🇰🇳', code: 'KN', currency: 'Dólar del Caribe Oriental',currencyCode: 'XCD', currencySymbol: '\$', minWagePerHour: 8),
  Country(name: 'San Marino',           flag: '🇸🇲', code: 'SM', currency: 'Euro',                    currencyCode: 'EUR', currencySymbol: '€',  minWagePerHour: 10),
  Country(name: 'San Vicente',          flag: '🇻🇨', code: 'VC', currency: 'Dólar del Caribe Oriental',currencyCode: 'XCD', currencySymbol: '\$', minWagePerHour: 6),
  Country(name: 'Santa Lucía',          flag: '🇱🇨', code: 'LC', currency: 'Dólar del Caribe Oriental',currencyCode: 'XCD', currencySymbol: '\$', minWagePerHour: 7),
  Country(name: 'Santo Tomé y Príncipe',flag: '🇸🇹', code: 'ST', currency: 'Dobra de Santo Tomé',    currencyCode: 'STN', currencySymbol: 'Db', minWagePerHour: 30),
  Country(name: 'Senegal',              flag: '🇸🇳', code: 'SN', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 400),
  Country(name: 'Serbia',               flag: '🇷🇸', code: 'RS', currency: 'Dinar serbio',            currencyCode: 'RSD', currencySymbol: 'дин',minWagePerHour: 200),
  Country(name: 'Seychelles',           flag: '🇸🇨', code: 'SC', currency: 'Rupia de Seychelles',     currencyCode: 'SCR', currencySymbol: 'Rs', minWagePerHour: 35),
  Country(name: 'Sierra Leona',         flag: '🇸🇱', code: 'SL', currency: 'Leone de Sierra Leona',   currencyCode: 'SLE', currencySymbol: 'Le', minWagePerHour: 700),
  Country(name: 'Singapur',             flag: '🇸🇬', code: 'SG', currency: 'Dólar de Singapur',       currencyCode: 'SGD', currencySymbol: '\$',  minWagePerHour: 9),
  Country(name: 'Siria',                flag: '🇸🇾', code: 'SY', currency: 'Libra siria',             currencyCode: 'SYP', currencySymbol: '£',  minWagePerHour: 2000),
  Country(name: 'Somalia',              flag: '🇸🇴', code: 'SO', currency: 'Chelín somalí',           currencyCode: 'SOS', currencySymbol: 'Sh', minWagePerHour: 500),
  Country(name: 'Sri Lanka',            flag: '🇱🇰', code: 'LK', currency: 'Rupia de Sri Lanka',      currencyCode: 'LKR', currencySymbol: 'Rs', minWagePerHour: 370),
  Country(name: 'Sudáfrica',            flag: '🇿🇦', code: 'ZA', currency: 'Rand sudafricano',        currencyCode: 'ZAR', currencySymbol: 'R',  minWagePerHour: 27.58),
  Country(name: 'Sudán',                flag: '🇸🇩', code: 'SD', currency: 'Libra sudanesa',          currencyCode: 'SDG', currencySymbol: '£',  minWagePerHour: 700),
  Country(name: 'Sudán del Sur',        flag: '🇸🇸', code: 'SS', currency: 'Libra sursudanesa',       currencyCode: 'SSP', currencySymbol: '£',  minWagePerHour: 600),
  Country(name: 'Suecia',               flag: '🇸🇪', code: 'SE', currency: 'Corona sueca',            currencyCode: 'SEK', currencySymbol: 'kr', minWagePerHour: 150),
  Country(name: 'Suiza',                flag: '🇨🇭', code: 'CH', currency: 'Franco suizo',            currencyCode: 'CHF', currencySymbol: 'Fr', minWagePerHour: 24),
  Country(name: 'Surinam',              flag: '🇸🇷', code: 'SR', currency: 'Dólar de Surinam',        currencyCode: 'SRD', currencySymbol: '\$',  minWagePerHour: 18),
  Country(name: 'Tailandia',            flag: '🇹🇭', code: 'TH', currency: 'Baht tailandés',          currencyCode: 'THB', currencySymbol: '฿',  minWagePerHour: 100),
  Country(name: 'Tanzania',             flag: '🇹🇿', code: 'TZ', currency: 'Chelín tanzano',          currencyCode: 'TZS', currencySymbol: 'Sh', minWagePerHour: 800),
  Country(name: 'Tayikistán',           flag: '🇹🇯', code: 'TJ', currency: 'Somoni tayiko',           currencyCode: 'TJS', currencySymbol: 'SM', minWagePerHour: 7),
  Country(name: 'Timor Oriental',       flag: '🇹🇱', code: 'TL', currency: 'Dólar estadounidense',    currencyCode: 'USD', currencySymbol: '\$',  minWagePerHour: 1.15),
  Country(name: 'Togo',                 flag: '🇹🇬', code: 'TG', currency: 'Franco CFA de África Occidental', currencyCode: 'XOF', currencySymbol: 'Fr', minWagePerHour: 280),
  Country(name: 'Tonga',                flag: '🇹🇴', code: 'TO', currency: 'Paʻanga tongano',         currencyCode: 'TOP', currencySymbol: 'T\$', minWagePerHour: 5),
  Country(name: 'Trinidad y Tobago',    flag: '🇹🇹', code: 'TT', currency: 'Dólar de Trinidad y Tobago',currencyCode: 'TTD', currencySymbol: '\$',minWagePerHour: 22),
  Country(name: 'Túnez',                flag: '🇹🇳', code: 'TN', currency: 'Dinar tunecino',          currencyCode: 'TND', currencySymbol: 'د.ت',minWagePerHour: 5),
  Country(name: 'Turkmenistán',         flag: '🇹🇲', code: 'TM', currency: 'Manat turcomano',         currencyCode: 'TMT', currencySymbol: 'T',  minWagePerHour: 3),
  Country(name: 'Turquía',              flag: '🇹🇷', code: 'TR', currency: 'Lira turca',              currencyCode: 'TRY', currencySymbol: '₺',  minWagePerHour: 130),
  Country(name: 'Tuvalu',               flag: '🇹🇻', code: 'TV', currency: 'Dólar australiano',       currencyCode: 'AUD', currencySymbol: '\$',  minWagePerHour: 4),
  Country(name: 'Ucrania',              flag: '🇺🇦', code: 'UA', currency: 'Grivna ucraniana',         currencyCode: 'UAH', currencySymbol: '₴',  minWagePerHour: 90),
  Country(name: 'Uganda',               flag: '🇺🇬', code: 'UG', currency: 'Chelín ugandés',          currencyCode: 'UGX', currencySymbol: 'Sh', minWagePerHour: 2000),
  Country(name: 'Uruguay',              flag: '🇺🇾', code: 'UY', currency: 'Peso uruguayo',           currencyCode: 'UYU', currencySymbol: '\$',  minWagePerHour: 110),
  Country(name: 'Uzbekistán',           flag: '🇺🇿', code: 'UZ', currency: 'Som uzbeko',              currencyCode: 'UZS', currencySymbol: 'сўм',minWagePerHour: 2500),
  Country(name: 'Vanuatu',              flag: '🇻🇺', code: 'VU', currency: 'Vatu vanuatense',         currencyCode: 'VUV', currencySymbol: 'Vt', minWagePerHour: 500),
  Country(name: 'Venezuela',            flag: '🇻🇪', code: 'VE', currency: 'Bolívar venezolano',      currencyCode: 'VES', currencySymbol: 'Bs', minWagePerHour: 5),
  Country(name: 'Vietnam',              flag: '🇻🇳', code: 'VN', currency: 'Dong vietnamita',         currencyCode: 'VND', currencySymbol: '₫',  minWagePerHour: 25000),
  Country(name: 'Yemen',                flag: '🇾🇪', code: 'YE', currency: 'Riyal yemení',            currencyCode: 'YER', currencySymbol: '﷼', minWagePerHour: 1200),
  Country(name: 'Yibuti',               flag: '🇩🇯', code: 'DJ', currency: 'Franco yibutiano',        currencyCode: 'DJF', currencySymbol: 'Fr', minWagePerHour: 350),
  Country(name: 'Zambia',               flag: '🇿🇲', code: 'ZM', currency: 'Kwacha zambiano',         currencyCode: 'ZMW', currencySymbol: 'ZK', minWagePerHour: 14),
  Country(name: 'Zimbabue',             flag: '🇿🇼', code: 'ZW', currency: 'Dólar de Zimbabue',       currencyCode: 'ZWL', currencySymbol: '\$',  minWagePerHour: 750),
];

/// Busca un país por su código ISO
Country? countryByCode(String code) {
  try {
    return kCountries.firstWhere(
        (c) => c.code.toUpperCase() == code.toUpperCase());
  } catch (_) {
    return null;
  }
}